# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new',
            field=models.IntegerField(default=0),
        ),
    ]
