# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20171208_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='new',
            new_name='is_new',
        ),
    ]
